### ISSUE TITLE
Not compiled when installed from GitHub

### ISSUE THREAD

**Issue by codebling** [skidding/react-component-tree#19]
The latest published version of your module is substantially older, so I tried installing from GitHub `npm i --save https://github.com/skidding/react-component-tree#4335279` (had to use a commit ref as there are no tags). 

This results in `Error: Cannot find module 'react-component-tree'` on first run. This is because the `prepublish` is never run when the module is installed like this, and so the `dist` directory is never created/populated, resulting in a require of a non-existant file. 

I've forked and call `compile` on `install`, but still can't get the compile command to execute. When installed in this way, `babel -d dist/ src/` complains `src/ doesn't exist`, I'm not sure why.

Looking at how other modules do this, 
(use this one-liner to see the npm scripts for each of the modules in your current project *that have a dist directory*: `for i in $( find . -name dist | grep -Eo '\./.++/'); do echo $i; node -e "console.log(require('$i' + 'package.json').scripts)"; done;`
it seems that most modules simply commit their dist directories.

**Comment by codebling** [comment]
Looking at the source quickly, it seems as if babel might not be required anyhow?

**Comment by skidding** [comment]
@codebling this repo is deprecated, but I unfortunately didn't manage to update the README yet. 

All React Cosmos-related packages moved into a monolithic repo: [React Cosmos](https://github.com/skidding/react-cosmos). ReactComponentTree is still a [separate package](https://github.com/skidding/react-cosmos/tree/master/packages/react-component-tree), published latest under `1.0.0-beta.2` (since we're preparing a big `1.0` React Cosmos release).

**Comment by codebling** [comment]
Cool, except same problem. `"main": "lib/index.js",` and no `lib` directory. How is this even working for You?

**Comment by codebling** [comment]
I'm going to update this package or create a similar version -- serialising the React component tree state is needed on an isomorphic servers if you're not passing initial state through props. Passing initial state through props breaks encapsulation/reusability for React components, since parent components need to know in advance what its children and childrens' children are, so that it can pass along the props.
